apiVersion: v1
kind: ConfigMap
metadata:
 name: tempo-config
data:
 tempo-overrides: |
  overrides:
   "single-tenant":
      search_tags_allow_list:
        - "instance"
      ingestion_rate_strategy: "local"
      ingestion_rate_limit_bytes: 15000000
      ingestion_burst_size_bytes: 20000000
      max_traces_per_user: 10000
      max_global_traces_per_user: 0
      max_bytes_per_trace: 50000
      max_search_bytes_per_trace: 0
      max_bytes_per_tag_values_query: 5000000
      block_retention: 0s
 tempo-config: |
  server:
    http_listen_port: 3200

  distributor:
    search_tags_deny_list:
      - "instance"
      - "version"
    receivers:
      jaeger:
        protocols:
          thrift_http:
          grpc:
          thrift_binary:
          thrift_compact:
      zipkin:
      otlp:
        protocols:
          http:
          grpc:
      opencensus:

  ingester:
    trace_idle_period: 10s
    max_block_bytes: 1_000_000
    max_block_duration: 5m

  compactor:
    compaction:
      compaction_window: 1h
      max_block_bytes: 100_000_000
      block_retention: 1h
      compacted_block_retention: 10m

  storage:
    trace:
      backend: local
      #block:
      #  bloom_filter_false_positive: .05
      #  index_downsample_bytes: 1000
      #  encoding: zstd
      wal:
        path: /tmp/tempo/wal
        #encoding: snappy
      local:
        path: /tmp/tempo/blocks
      pool:
        max_workers: 100
        queue_depth: 10000

  overrides:
    per_tenant_override_config: /data/tempo-overrides.yaml

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      volumes :
        - name: tempo-config-vol
          configMap:
            name: tempo-config
            items:
              - key: tempo-config
                path: tempo-config.yaml
              - key : tempo-overrides
                path : tempo-overrides.yaml
      containers:
      - name: tempo
        image: grafana/tempo:2.0.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /data
            name: tempo-config-vol
        command:
          - '/tempo'
          - '-config.file=/data/tempo-config.yaml'
        ports:
          - containerPort: 3200
            name: "status-port"
          - containerPort : 4317
            name : "otlp-grpc"
        
---

apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: default
spec:
  type: ClusterIP #NodePort #LoadBalancer
  selector:
    app: tempo
  ports:
  - port: 4317
    targetPort: 4317
    name : "otlp-grpc"
  - port : 3200
    targetPort: 3200
    name : "status-port"