global:
  # How frequently to scrape targets
  scrape_interval: 15s
  # How frequently to evaluate rules
  evaluation_interval: 15s

# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yml


scrape_configs:
  - job_name: 'collector'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'otel-collector:6666' ]
  #- job_name: 'cloudwatch'
  #  scrape_interval: 5s
  #  static_configs:
  #    - targets: [ 'cloudwatch-exporter:9106' ]