#https://stackoverflow.com/questions/74991374/prometheus-is-not-reading-otel-data
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555
      http:
        endpoint: 0.0.0.0:5556

connectors:
  spanmetrics:
    #metrics_exporter: prometheus
    #latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    dimensions:
      - name: http.method
        #default: GET
      - name: http.status_code
      - name: http.route
      - name: otel.library.name
    dimensions_cache_size: 1000
    #aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"   
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"   
    exemplars:
      enabled: true
      
exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: 0.0.0.0:6666
    namespace: default
    enable_open_metrics : true
    resource_to_telemetry_conversion :
      enabled : false
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
    traces/in:
      receivers: [otlp]
      exporters: [spanmetrics]
    metrics/out:
      receivers: [spanmetrics]
      exporters: [prometheus]