{
 "title": "JVM Overview (OpenTelemetry)",
 "description": "Dashboard for JVM metrics with Prometheus / OpenTelemetry instrumentation",
 "tags": [
  "JVM",
  "open-telemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(default_process_runtime_jvm_memory_usage,exported_job)"
    }
   },
   {
    "name": "gc_action",
    "query": {
     "query": "label_values(default_process_runtime_jvm_gc_duration_bucket{instance=\"$instance\"},action)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "default_process_runtime_jvm_system_cpu_utilization{exported_job=\"$instance\"}",
     "legendFormat": "CPU utilization (whole system)"
    },
    {
     "expr": "process_runtime_jvm_cpu_utilization{instance=\"$instance\"}",
     "legendFormat": "JVM CPU utilization"
    }
   ]
  },
  {
   "title": "Average CPU load of the whole system for the last minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "default_process_runtime_jvm_system_cpu_load_1m{exported_job=\"$instance\"}",
     "legendFormat": "Average CPU load"
    }
   ]
  },
  { "title": "Memory pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Heap memory used / commited / max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(default_process_runtime_jvm_memory_usage{exported_job=\"$instance\",type=\"heap\"})",
     "legendFormat": "Heap used"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_committed{instance=\"$instance\",type=\"heap\"})",
     "legendFormat": "Heap committed"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_limit{instance=\"$instance\",type=\"heap\"})",
     "legendFormat": "Heap max obtainable"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "default_process_runtime_jvm_memory_usage{exported_job=\"$instance\"}",
     "legendFormat": "{{ type }} - {{ pool }}"
    }
   ]
  },
  {
   "title": "Memory committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "default_process_runtime_jvm_memory_committed{exported_job=\"$instance\"}",
     "legendFormat": "{{ type }} - {{ pool }}"
    }
   ]
  },
  {
   "title": "Max obtainable memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "default_process_runtime_jvm_memory_limit{exported_job=\"$instance\"}",
     "legendFormat": "{{ type }} - {{ pool }}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Number of executing threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "default_process_runtime_jvm_threads_count{exported_job=\"$instance\"}",
     "legendFormat": "Daemon: {{daemon}}"
    }
   ]
  },
  { "title": "Garbage collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "JVM garbage collection duration - $gc_action",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "repeat": "gc_action",
   "targets": [
    {
     "expr": "sum(round(rate(default_process_runtime_jvm_gc_duration_bucket{exported_job=\"$instance\", gc=\"G1 Young Generation\"}[$__interval]) * $__interval_ms / 1000)) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Number of classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "default_process_runtime_jvm_classes_current_loaded{exported_job=\"$instance\"}",
     "legendFormat": "Currently loaded"
    },
    {
     "expr": "process_runtime_jvm_classes_loaded_total{instance=\"$instance\"}",
     "legendFormat": "Loaded since JVM start"
    },
    {
     "expr": "process_runtime_jvm_classes_unloaded_total{instance=\"$instance\"}",
     "legendFormat": "Unloaded since JVM start"
    }
   ]
  }
 ]
}