{
 "title": "APM - Production",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(default_duration_count, service_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Service Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(sum by (http_route, http_method) (rate(default_duration_sum{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name='$service_name'}[5m]))/sum by (http_route, http_method) (rate(default_duration_count{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name='$service_name'}[5m])> 0))",
     "legendFormat": "{{http_method}}  {{http_route}}"
    }
   ]
  },
  {
   "title": "Request Per Sec for a service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service_name)(rate(default_calls{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name='$service_name'}[5m]))",
     "legendFormat": "{{http_route}} {{http_method}}"
    }
   ]
  },
  {
   "title": "Error rate for a service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((sum by (service_name) (rate(default_duration_count{ http_status_code=~\"5.*|4.*\", span_kind=~\"SPAN_KIND_SERVER\", service_name=\"$service_name\", http_method=~\"GET|POST|PUT|DELETE\"}[5m]))/sum by (service_name) (rate(default_duration_count{span_kind=~\"SPAN_KIND_SERVER\", service_name=\"$service_name\", http_method=~\"GET|POST|PUT|DELETE\"}[5m]))) > 0)",
     "legendFormat": "{{http_route}} {{http_method}}"
    }
   ]
  },
  {
   "title": "Requests Average Durations",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_route, http_method) (rate(default_duration_sum{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name='$service_name'}[5m]))/sum by (http_route, http_method) (rate(default_duration_count{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name='$service_name'}[5m]) >0) ",
     "legendFormat": "{{http_method}}  {{http_route}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_route, http_method)(rate(default_calls{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name=\"$service_name\"}[5m]))",
     "legendFormat": "{{http_route}} {{http_method}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(default_calls{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 18, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_method, http_route) (default_calls{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name=\"$service_name\"})",
     "legendFormat": "{{http_route}} {{http_method}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_route, http_method) (default_duration_count{ http_status_code=~\"2.*\", span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name=\"$service_name\"}) / sum by(http_route, http_method) (default_duration_count{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name=\"$service_name\"})",
     "legendFormat": "{{http_route}} {{http_method}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(default_duration_count{status_code=\"STATUS_CODE_ERROR\",http_method=~\"GET|POST|PUT|DELETE\", service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Percent HTTP errors ( 4x and 5x)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((sum by (http_route) (rate(default_duration_count{ http_status_code=~\"5.*|4.*\", span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name=\"$service_name\"}[5m]))/sum by (http_route) (rate(default_duration_count{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name=\"$service_name\"}[5m]))) > 0)",
     "legendFormat": "{{http_route}} {{http_method}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(default_duration_bucket{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name=\"$service_name\"}[5m])) by(http_route,http_method, le))",
     "legendFormat": "{{http_route}} {{http_method}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(default_duration_bucket{span_kind=~\"SPAN_KIND_SERVER\",http_method=~\"GET|POST|PUT|DELETE\", service_name=\"$service_name\"}[5m])) by(http_route, http_method, le))",
     "legendFormat": "{{http_route}} {{http_method}}"
    }
   ]
  },
  {
   "title": "Top 10 Highest DB Operation Latencies Over Last Minute",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, sum by (span_name)(increase(default_duration_sum{span_name=~\".*Repository.*|.*mongoose.*|.*mongodb.*\", service_name=\"$service_name\"}[5m]) / increase(default_duration_count{span_name=~\".*Repository.*|.*mongoose.*|.*mongodb.*\", service_name=\"$service_name\"}[5m])> 0) != inf )"
    }
   ]
  },
  {
   "title": "Top 10 Highest API Operation Latencies Over Last Minute",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, sum by (span_name)(increase(default_duration_sum{span_name=~\"GET .*|PUT .*|POST .*|DELETE .*\", service_name=\"$service_name\"}[5m]) / increase(default_duration_count{span_name=~\"GET .*|PUT .*|POST .*|DELETE .*\", service_name=\"$service_name\"}[5m]) != inf ))"
    }
   ]
  }
 ]
}